-- CreateTable
CREATE TABLE "AlokasiTKD" (
    "id" SERIAL NOT NULL,
    "pemda" TEXT NOT NULL,
    "dbh" DOUBLE PRECISION NOT NULL,
    "dau" DOUBLE PRECISION NOT NULL,
    "dakFisik" DOUBLE PRECISION NOT NULL,
    "dakNonfisik" DOUBLE PRECISION NOT NULL,
    "danaDesa" DOUBLE PRECISION NOT NULL,
    "infis" DOUBLE PRECISION NOT NULL,
    "total" DOUBLE PRECISION NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "AlokasiTKD_pkey" PRIMARY KEY ("id")
);
